version: "3.7"

services:
  app:
    container_name: find-cheap-car
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.1-alpine
    container_name: find-cheap-car-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432

  redis:
    image: redis:6.2.4-alpine
    container_name: find-cheap-car-redis
    restart: always
    expose:
      - 6379

volumes:
  postgres_data:
