"""create tables brands, models

Revision ID: 778524b25c88
Revises: 80bb7ae99199
Create Date: 2021-06-10 02:58:14.127384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778524b25c88'
down_revision = '80bb7ae99199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    brands_table = op.create_table('brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    models_table = op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # insert brands
    op.bulk_insert(
        brands_table,
        [
            {
                "id": 1,
                "name": "Acura"
            },
            {
                "id": 2,
                "name": "Alfa Romeo"
            },
            {
                "id": 3,
                "name": "AMC"
            },
            {
                "id": 4,
                "name": "Aston Martin"
            },
            {
                "id": 5,
                "name": "Audi"
            },
            {
                "id": 6,
                "name": "Avanti"
            },
            {
                "id": 7,
                "name": "Bentley"
            },
            {
                "id": 8,
                "name": "BMW"
            },
            {
                "id": 9,
                "name": "Buick"
            },
            {
                "id": 10,
                "name": "Cadillac"
            },
            {
                "id": 11,
                "name": "Chevrolet"
            },
            {
                "id": 12,
                "name": "Chrysler"
            },
            {
                "id": 13,
                "name": "Daewoo"
            },
            {
                "id": 14,
                "name": "Daihatsu"
            },
            {
                "id": 15,
                "name": "Datsun"
            },
            {
                "id": 16,
                "name": "DeLorean"
            },
            {
                "id": 17,
                "name": "Dodge"
            },
            {
                "id": 18,
                "name": "Eagle"
            },
            {
                "id": 19,
                "name": "Ferrari"
            },
            {
                "id": 20,
                "name": "FIAT"
            },
            {
                "id": 21,
                "name": "Fisker"
            },
            {
                "id": 22,
                "name": "Ford"
            },
            {
                "id": 23,
                "name": "Freightliner"
            },
            {
                "id": 24,
                "name": "Geo"
            },
            {
                "id": 25,
                "name": "GMC"
            },
            {
                "id": 26,
                "name": "Honda"
            },
            {
                "id": 27,
                "name": "Hummer"
            },
            {
                "id": 28,
                "name": "Hyundai"
            },
            {
                "id": 29,
                "name": "Infiniti"
            },
            {
                "id": 30,
                "name": "Isuzu"
            },
            {
                "id": 31,
                "name": "Jaguar"
            },
            {
                "id": 32,
                "name": "Jeep"
            },
            {
                "id": 33,
                "name": "Kia"
            },
            {
                "id": 34,
                "name": "Lamborghini"
            },
            {
                "id": 35,
                "name": "Lancia"
            },
            {
                "id": 36,
                "name": "Land Rover"
            },
            {
                "id": 37,
                "name": "Lexus"
            },
            {
                "id": 38,
                "name": "Lincoln"
            },
            {
                "id": 39,
                "name": "Lotus"
            },
            {
                "id": 40,
                "name": "Maserati"
            },
            {
                "id": 41,
                "name": "Maybach"
            },
            {
                "id": 42,
                "name": "Mazda"
            },
            {
                "id": 43,
                "name": "McLaren"
            },
            {
                "id": 44,
                "name": "Mercedes-Benz"
            },
            {
                "id": 45,
                "name": "Mercury"
            },
            {
                "id": 46,
                "name": "Merkur"
            },
            {
                "id": 47,
                "name": "Mini"
            },
            {
                "id": 48,
                "name": "Mitsubishi"
            },
            {
                "id": 49,
                "name": "Nissan"
            },
            {
                "id": 50,
                "name": "Oldsmobile"
            },
            {
                "id": 51,
                "name": "Peugeot"
            },
            {
                "id": 52,
                "name": "Plymouth"
            },
            {
                "id": 53,
                "name": "Pontiac"
            },
            {
                "id": 54,
                "name": "Porsche"
            },
            {
                "id": 55,
                "name": "RAM"
            },
            {
                "id": 56,
                "name": "Renault"
            },
            {
                "id": 57,
                "name": "Rolls-Royce"
            },
            {
                "id": 58,
                "name": "Saab"
            },
            {
                "id": 59,
                "name": "Saturn"
            },
            {
                "id": 60,
                "name": "Scion"
            },
            {
                "id": 61,
                "name": "Smart"
            },
            {
                "id": 62,
                "name": "SRT"
            },
            {
                "id": 63,
                "name": "Sterling"
            },
            {
                "id": 64,
                "name": "Subaru"
            },
            {
                "id": 65,
                "name": "Suzuki"
            },
            {
                "id": 66,
                "name": "Tesla"
            },
            {
                "id": 67,
                "name": "Toyota"
            },
            {
                "id": 68,
                "name": "Triumph"
            },
            {
                "id": 69,
                "name": "Volkswagen"
            },
            {
                "id": 70,
                "name": "Volvo"
            },
            {
                "id": 71,
                "name": "Yugo"
            },
        ]
    )

    # insert models
    op.bulk_insert(
        models_table,
        [
            {
                "id": 1,
                "name": "2.2CL",
                "brand_id": 1
            },
            {
                "id": 2,
                "name": "2.3CL",
                "brand_id": 1
            },
            {
                "id": 3,
                "name": "3.0CL",
                "brand_id": 1
            },
            {
                "id": 4,
                "name": "3.2CL",
                "brand_id": 1
            },
            {
                "id": 5,
                "name": "ILX",
                "brand_id": 1
            },
            {
                "id": 6,
                "name": "Integra",
                "brand_id": 1
            },

            {
                "id": 7,
                "name": "Legend",
                "brand_id": 1
            },
            {
                "id": 8,
                "name": "MDX",
                "brand_id": 1
            },
            {
                "id": 9,
                "name": "NSX",
                "brand_id": 1
            },
            {
                "id": 10,
                "name": "RDX",
                "brand_id": 1
            },
            {
                "id": 11,
                "name": "3.5 RL",
                "brand_id": 1
            },
            {
                "id": 12,
                "name": "RL",
                "brand_id": 1
            },
            {
                "id": 13,
                "name": "RSX",
                "brand_id": 1
            },
            {
                "id": 14,
                "name": "SLX",
                "brand_id": 1
            },
            {
                "id": 15,
                "name": "2.5TL",
                "brand_id": 1
            },
            {
                "id": 16,
                "name": "3.2TL",
                "brand_id": 1
            },
            {
                "id": 17,
                "name": "TL",
                "brand_id": 1
            },
            {
                "id": 18,
                "name": "TSX",
                "brand_id": 1
            },
            {
                "id": 19,
                "name": "Vigor",
                "brand_id": 1
            },
            {
                "id": 20,
                "name": "ZDX",
                "brand_id": 1
            },
            {
                "id": 21,
                "name": "164",
                "brand_id": 2
            },
            {
                "id": 22,
                "name": "8C Competizione",
                "brand_id": 2
            },
            {
                "id": 23,
                "name": "GTV-6",
                "brand_id": 2
            },
            {
                "id": 24,
                "name": "Milano",
                "brand_id": 2
            },
            {
                "id": 25,
                "name": "Spider",
                "brand_id": 2
            },
            {
                "id": 26,
                "name": "Alliance",
                "brand_id": 3
            },
            {
                "id": 27,
                "name": "Concord",
                "brand_id": 3
            },
            {
                "id": 28,
                "name": "Eagle",
                "brand_id": 3
            },
            {
                "id": 29,
                "name": "Encore",
                "brand_id": 3
            },
            {
                "id": 30,
                "name": "Spirit",
                "brand_id": 3
            },
            {
                "id": 31,
                "name": "DB7",
                "brand_id": 4
            },
            {
                "id": 32,
                "name": "DB9",
                "brand_id": 4
            },
            {
                "id": 33,
                "name": "DBS",
                "brand_id": 4
            },
            {
                "id": 34,
                "name": "Lagonda",
                "brand_id": 4
            },
            {
                "id": 35,
                "name": "Rapide",
                "brand_id": 4
            },
            {
                "id": 36,
                "name": "V12 Vantage",
                "brand_id": 4
            },
            {
                "id": 37,
                "name": "V8 Vantage",
                "brand_id": 4
            },
            {
                "id": 38,
                "name": "Vanquish",
                "brand_id": 4
            },
            {
                "id": 39,
                "name": "Virage",
                "brand_id": 4
            },
            {
                "id": 40,
                "name": "100",
                "brand_id": 5
            },
            {
                "id": 41,
                "name": "200",
                "brand_id": 5
            },
            {
                "id": 42,
                "name": "4000",
                "brand_id": 5
            },
            {
                "id": 43,
                "name": "5000",
                "brand_id": 5
            },
            {
                "id": 44,
                "name": "80",
                "brand_id": 5
            },
            {
                "id": 45,
                "name": "90",
                "brand_id": 5
            },
            {
                "id": 46,
                "name": "A3",
                "brand_id": 5
            },
            {
                "id": 47,
                "name": "A4",
                "brand_id": 5
            },
            {
                "id": 48,
                "name": "A5",
                "brand_id": 5
            },
            {
                "id": 49,
                "name": "A6",
                "brand_id": 5
            },
            {
                "id": 50,
                "name": "A7",
                "brand_id": 5
            },
            {
                "id": 51,
                "name": "A8",
                "brand_id": 5
            },
            {
                "id": 52,
                "name": "allroad",
                "brand_id": 5
            },
            {
                "id": 53,
                "name": "Cabriolet",
                "brand_id": 5
            },
            {
                "id": 54,
                "name": "Coupe",
                "brand_id": 5
            },
            {
                "id": 55,
                "name": "Q3",
                "brand_id": 5
            },
            {
                "id": 56,
                "name": "Q5",
                "brand_id": 5
            },
            {
                "id": 57,
                "name": "Q7",
                "brand_id": 5
            },
            {
                "id": 58,
                "name": "Quattro",
                "brand_id": 5
            },
            {
                "id": 59,
                "name": "R8",
                "brand_id": 5
            },
            {
                "id": 60,
                "name": "RS 4",
                "brand_id": 5
            },
            {
                "id": 61,
                "name": "RS 5",
                "brand_id": 5
            },
            {
                "id": 62,
                "name": "RS 6",
                "brand_id": 5
            },
            {
                "id": 63,
                "name": "S4",
                "brand_id": 5
            },
            {
                "id": 64,
                "name": "S5",
                "brand_id": 5
            },
            {
                "id": 65,
                "name": "S6",
                "brand_id": 5
            },
            {
                "id": 66,
                "name": "S7",
                "brand_id": 5
            },
            {
                "id": 67,
                "name": "S8",
                "brand_id": 5
            },
            {
                "id": 68,
                "name": "TT",
                "brand_id": 5
            },
            {
                "id": 69,
                "name": "TT RS",
                "brand_id": 5
            },
            {
                "id": 70,
                "name": "TTS",
                "brand_id": 5
            },
            {
                "id": 71,
                "name": "V8 Quattro",
                "brand_id": 5
            },
            {
                "id": 72,
                "name": "Convertible",
                "brand_id": 6
            },
            {
                "id": 73,
                "name": "Coupe",
                "brand_id": 6
            },
            {
                "id": 74,
                "name": "Sedan",
                "brand_id": 6
            },
            {
                "id": 75,
                "name": "Arnage",
                "brand_id": 7
            },
            {
                "id": 76,
                "name": "Azure",
                "brand_id": 7
            },
            {
                "id": 77,
                "name": "Brooklands",
                "brand_id": 7
            },
            {
                "id": 78,
                "name": "Continental",
                "brand_id": 7
            },
            {
                "id": 79,
                "name": "Corniche",
                "brand_id": 7
            },
            {
                "id": 80,
                "name": "Eight",
                "brand_id": 7
            },
            {
                "id": 81,
                "name": "Mulsanne",
                "brand_id": 7
            },
            {
                "id": 82,
                "name": "Turbo R",
                "brand_id": 7
            },
            {
                "id": 83,
                "name": "128i",
                "brand_id": 8
            },
            {
                "id": 84,
                "name": "135i",
                "brand_id": 8
            },
            {
                "id": 85,
                "name": "135is",
                "brand_id": 8
            },
            {
                "id": 86,
                "name": "318i",
                "brand_id": 8
            },
            {
                "id": 87,
                "name": "318iC",
                "brand_id": 8
            },
            {
                "id": 88,
                "name": "318iS",
                "brand_id": 8
            },
            {
                "id": 89,
                "name": "318ti",
                "brand_id": 8
            },
            {
                "id": 90,
                "name": "320i",
                "brand_id": 8
            },
            {
                "id": 91,
                "name": "323ci",
                "brand_id": 8
            },
            {
                "id": 92,
                "name": "323i",
                "brand_id": 8
            },
            {
                "id": 93,
                "name": "323is",
                "brand_id": 8
            },
            {
                "id": 94,
                "name": "323iT",
                "brand_id": 8
            },
            {
                "id": 95,
                "name": "325Ci",
                "brand_id": 8
            },
            {
                "id": 96,
                "name": "325e",
                "brand_id": 8
            },
            {
                "id": 97,
                "name": "325es",
                "brand_id": 8
            },
            {
                "id": 98,
                "name": "325i",
                "brand_id": 8
            },
            {
                "id": 99,
                "name": "325is",
                "brand_id": 8
            },
            {
                "id": 100,
                "name": "325iX",
                "brand_id": 8
            },
            {
                "id": 101,
                "name": "325xi",
                "brand_id": 8
            },
            {
                "id": 102,
                "name": "328Ci",
                "brand_id": 8
            },
            {
                "id": 103,
                "name": "328i",
                "brand_id": 8
            },
            {
                "id": 104,
                "name": "328iS",
                "brand_id": 8
            },
            {
                "id": 105,
                "name": "328xi",
                "brand_id": 8
            },
            {
                "id": 106,
                "name": "330Ci",
                "brand_id": 8
            },
            {
                "id": 107,
                "name": "330i",
                "brand_id": 8
            },
            {
                "id": 108,
                "name": "330xi",
                "brand_id": 8
            },
            {
                "id": 109,
                "name": "335d",
                "brand_id": 8
            },
            {
                "id": 110,
                "name": "335i",
                "brand_id": 8
            },
            {
                "id": 111,
                "name": "335is",
                "brand_id": 8
            },
            {
                "id": 112,
                "name": "335xi",
                "brand_id": 8
            },
            {
                "id": 113,
                "name": "ActiveHybrid 3",
                "brand_id": 8
            },
            {
                "id": 114,
                "name": "325",
                "brand_id": 8
            },
            {
                "id": 115,
                "name": "524td",
                "brand_id": 8
            },
            {
                "id": 116,
                "name": "525i",
                "brand_id": 8
            },
            {
                "id": 117,
                "name": "525xi",
                "brand_id": 8
            },
            {
                "id": 118,
                "name": "528e",
                "brand_id": 8
            },
            {
                "id": 119,
                "name": "528i",
                "brand_id": 8
            },
            {
                "id": 120,
                "name": "528iT",
                "brand_id": 8
            },
            {
                "id": 121,
                "name": "528xi",
                "brand_id": 8
            },
            {
                "id": 122,
                "name": "530i",
                "brand_id": 8
            },
            {
                "id": 123,
                "name": "530iT",
                "brand_id": 8
            },
            {
                "id": 124,
                "name": "530xi",
                "brand_id": 8
            },
            {
                "id": 125,
                "name": "533i",
                "brand_id": 8
            },
            {
                "id": 126,
                "name": "535i",
                "brand_id": 8
            },
            {
                "id": 127,
                "name": "535i Gran Turismo",
                "brand_id": 8
            },
            {
                "id": 128,
                "name": "535xi",
                "brand_id": 8
            },
            {
                "id": 129,
                "name": "540i",
                "brand_id": 8
            },
            {
                "id": 130,
                "name": "545i",
                "brand_id": 8
            },
            {
                "id": 131,
                "name": "550i",
                "brand_id": 8
            },
            {
                "id": 132,
                "name": "550i Gran Turismo",
                "brand_id": 8
            },
            {
                "id": 133,
                "name": "ActiveHybrid 5",
                "brand_id": 8
            },
            {
                "id": 134,
                "name": "633CSi",
                "brand_id": 8
            },
            {
                "id": 135,
                "name": "635CSi",
                "brand_id": 8
            },
            {
                "id": 136,
                "name": "640i",
                "brand_id": 8
            },
            {
                "id": 137,
                "name": "640i Gran Coupe",
                "brand_id": 8
            },
            {
                "id": 138,
                "name": "645Ci",
                "brand_id": 8
            },
            {
                "id": 139,
                "name": "650i",
                "brand_id": 8
            },
            {
                "id": 140,
                "name": "650i Gran Coupe",
                "brand_id": 8
            },
            {
                "id": 141,
                "name": "L6",
                "brand_id": 8
            },
            {
                "id": 142,
                "name": "733i",
                "brand_id": 8
            },
            {
                "id": 143,
                "name": "735i",
                "brand_id": 8
            },
            {
                "id": 144,
                "name": "735iL",
                "brand_id": 8
            },
            {
                "id": 145,
                "name": "740i",
                "brand_id": 8
            },
            {
                "id": 146,
                "name": "740iL",
                "brand_id": 8
            },
            {
                "id": 147,
                "name": "740Li",
                "brand_id": 8
            },
            {
                "id": 148,
                "name": "745i",
                "brand_id": 8
            },
            {
                "id": 149,
                "name": "745Li",
                "brand_id": 8
            },
            {
                "id": 150,
                "name": "750i",
                "brand_id": 8
            },
            {
                "id": 151,
                "name": "750iL",
                "brand_id": 8
            },
            {
                "id": 152,
                "name": "750Li",
                "brand_id": 8
            },
            {
                "id": 153,
                "name": "760i",
                "brand_id": 8
            },
            {
                "id": 154,
                "name": "760Li",
                "brand_id": 8
            },
            {
                "id": 155,
                "name": "ActiveHybrid 7",
                "brand_id": 8
            },
            {
                "id": 156,
                "name": "Alpina B7",
                "brand_id": 8
            },
            {
                "id": 157,
                "name": "840Ci",
                "brand_id": 8
            },
            {
                "id": 158,
                "name": "850Ci",
                "brand_id": 8
            },
            {
                "id": 159,
                "name": "850CSi",
                "brand_id": 8
            },
            {
                "id": 160,
                "name": "850i",
                "brand_id": 8
            },
            {
                "id": 161,
                "name": "L7",
                "brand_id": 8
            },
            {
                "id": 162,
                "name": "1 Series M",
                "brand_id": 8
            },
            {
                "id": 163,
                "name": "M Coupe",
                "brand_id": 8
            },
            {
                "id": 164,
                "name": "M Roadster",
                "brand_id": 8
            },
            {
                "id": 165,
                "name": "M3",
                "brand_id": 8
            },
            {
                "id": 166,
                "name": "M5",
                "brand_id": 8
            },
            {
                "id": 167,
                "name": "M6",
                "brand_id": 8
            },
            {
                "id": 168,
                "name": "X5 M",
                "brand_id": 8
            },
            {
                "id": 169,
                "name": "X6 M",
                "brand_id": 8
            },
            {
                "id": 170,
                "name": "ActiveHybrid X6",
                "brand_id": 8
            },
            {
                "id": 171,
                "name": "X1",
                "brand_id": 8
            },
            {
                "id": 172,
                "name": "X3",
                "brand_id": 8
            },
            {
                "id": 173,
                "name": "X5",
                "brand_id": 8
            },
            {
                "id": 174,
                "name": "X6",
                "brand_id": 8
            },
            {
                "id": 175,
                "name": "Z3",
                "brand_id": 8
            },
            {
                "id": 176,
                "name": "Z4",
                "brand_id": 8
            },
            {
                "id": 177,
                "name": "Z8",
                "brand_id": 8
            },
            {
                "id": 178,
                "name": "Century",
                "brand_id": 9
            },
            {
                "id": 179,
                "name": "Electra",
                "brand_id": 9
            },
            {
                "id": 180,
                "name": "Enclave",
                "brand_id": 9
            },
            {
                "id": 181,
                "name": "Encore",
                "brand_id": 9
            },
            {
                "id": 182,
                "name": "LaCrosse",
                "brand_id": 9
            },
            {
                "id": 183,
                "name": "Le Sabre",
                "brand_id": 9
            },
            {
                "id": 184,
                "name": "Lucerne",
                "brand_id": 9
            },
            {
                "id": 185,
                "name": "Park Avenue",
                "brand_id": 9
            },
            {
                "id": 186,
                "name": "Rainier",
                "brand_id": 9
            },
            {
                "id": 187,
                "name": "Reatta",
                "brand_id": 9
            },
            {
                "id": 188,
                "name": "Regal",
                "brand_id": 9
            },
            {
                "id": 189,
                "name": "Rendezvous",
                "brand_id": 9
            },
            {
                "id": 190,
                "name": "Riviera",
                "brand_id": 9
            },
            {
                "id": 191,
                "name": "Roadmaster",
                "brand_id": 9
            },
            {
                "id": 192,
                "name": "Skyhawk",
                "brand_id": 9
            },
            {
                "id": 193,
                "name": "Skylark",
                "brand_id": 9
            },
            {
                "id": 194,
                "name": "Somerset",
                "brand_id": 9
            },
            {
                "id": 195,
                "name": "Terraza",
                "brand_id": 9
            },
            {
                "id": 196,
                "name": "Verano",
                "brand_id": 9
            },
            {
                "id": 197,
                "name": "Allante",
                "brand_id": 10
            },
            {
                "id": 198,
                "name": "ATS",
                "brand_id": 10
            },
            {
                "id": 199,
                "name": "Brougham",
                "brand_id": 10
            },
            {
                "id": 200,
                "name": "Catera",
                "brand_id": 10
            },
            {
                "id": 201,
                "name": "Cimarron",
                "brand_id": 10
            },
            {
                "id": 202,
                "name": "CTS",
                "brand_id": 10
            },
            {
                "id": 203,
                "name": "De Ville",
                "brand_id": 10
            },
            {
                "id": 204,
                "name": "DTS",
                "brand_id": 10
            },
            {
                "id": 205,
                "name": "Eldorado",
                "brand_id": 10
            },
            {
                "id": 206,
                "name": "Escalade",
                "brand_id": 10
            },
            {
                "id": 207,
                "name": "Escalade ESV",
                "brand_id": 10
            },
            {
                "id": 208,
                "name": "Escalade EXT",
                "brand_id": 10
            },
            {
                "id": 209,
                "name": "Fleetwood",
                "brand_id": 10
            },
            {
                "id": 210,
                "name": "Seville",
                "brand_id": 10
            },
            {
                "id": 211,
                "name": "SRX",
                "brand_id": 10
            },
            {
                "id": 212,
                "name": "STS",
                "brand_id": 10
            },
            {
                "id": 213,
                "name": "XLR",
                "brand_id": 10
            },
            {
                "id": 214,
                "name": "XTS",
                "brand_id": 10
            },
            {
                "id": 215,
                "name": "Astro",
                "brand_id": 11
            },
            {
                "id": 216,
                "name": "Avalanche",
                "brand_id": 11
            },
            {
                "id": 217,
                "name": "Aveo",
                "brand_id": 11
            },
            {
                "id": 218,
                "name": "Aveo5",
                "brand_id": 11
            },
            {
                "id": 219,
                "name": "Beretta",
                "brand_id": 11
            },
            {
                "id": 220,
                "name": "Blazer",
                "brand_id": 11
            },
            {
                "id": 221,
                "name": "Camaro",
                "brand_id": 11
            },
            {
                "id": 222,
                "name": "Caprice",
                "brand_id": 11
            },
            {
                "id": 223,
                "name": "Captiva Sport",
                "brand_id": 11
            },
            {
                "id": 224,
                "name": "Cavalier",
                "brand_id": 11
            },
            {
                "id": 225,
                "name": "Celebrity",
                "brand_id": 11
            },
            {
                "id": 226,
                "name": "Chevette",
                "brand_id": 11
            },
            {
                "id": 227,
                "name": "Citation",
                "brand_id": 11
            },
            {
                "id": 228,
                "name": "Cobalt",
                "brand_id": 11
            },
            {
                "id": 229,
                "name": "Colorado",
                "brand_id": 11
            },
            {
                "id": 230,
                "name": "Corsica",
                "brand_id": 11
            },
            {
                "id": 231,
                "name": "Corvette",
                "brand_id": 11
            },
            {
                "id": 232,
                "name": "Cruze",
                "brand_id": 11
            },
            {
                "id": 233,
                "name": "El Camino",
                "brand_id": 11
            },
            {
                "id": 234,
                "name": "Equinox",
                "brand_id": 11
            },
            {
                "id": 235,
                "name": "Express Van",
                "brand_id": 11
            },
            {
                "id": 236,
                "name": "G Van",
                "brand_id": 11
            },
            {
                "id": 237,
                "name": "HHR",
                "brand_id": 11
            },
            {
                "id": 238,
                "name": "Impala",
                "brand_id": 11
            },
            {
                "id": 239,
                "name": "Kodiak C4500",
                "brand_id": 11
            },
            {
                "id": 240,
                "name": "Lumina",
                "brand_id": 11
            },
            {
                "id": 241,
                "name": "Lumina APV",
                "brand_id": 11
            },
            {
                "id": 242,
                "name": "LUV",
                "brand_id": 11
            },
            {
                "id": 243,
                "name": "Malibu",
                "brand_id": 11
            },
            {
                "id": 244,
                "name": "Metro",
                "brand_id": 11
            },
            {
                "id": 245,
                "name": "Monte Carlo",
                "brand_id": 11
            },
            {
                "id": 246,
                "name": "Nova",
                "brand_id": 11
            },
            {
                "id": 247,
                "name": "Prizm",
                "brand_id": 11
            },
            {
                "id": 248,
                "name": "S10 Blazer",
                "brand_id": 11
            },
            {
                "id": 249,
                "name": "S10 Pickup",
                "brand_id": 11
            },
            {
                "id": 250,
                "name": "Silverado and other C/K1500",
                "brand_id": 11
            },
            {
                "id": 251,
                "name": "Silverado and other C/K2500",
                "brand_id": 11
            },
            {
                "id": 252,
                "name": "Silverado and other C/K3500",
                "brand_id": 11
            },
            {
                "id": 253,
                "name": "Sonic",
                "brand_id": 11
            },
            {
                "id": 254,
                "name": "Spark",
                "brand_id": 11
            },
            {
                "id": 255,
                "name": "Spectrum",
                "brand_id": 11
            },
            {
                "id": 256,
                "name": "Sprint",
                "brand_id": 11
            },
            {
                "id": 257,
                "name": "SSR",
                "brand_id": 11
            },
            {
                "id": 258,
                "name": "Suburban",
                "brand_id": 11
            },
            {
                "id": 259,
                "name": "Tahoe",
                "brand_id": 11
            },
            {
                "id": 260,
                "name": "Tracker",
                "brand_id": 11
            },
            {
                "id": 261,
                "name": "TrailBlazer",
                "brand_id": 11
            },
            {
                "id": 262,
                "name": "TrailBlazer EXT",
                "brand_id": 11
            },
            {
                "id": 263,
                "name": "Traverse",
                "brand_id": 11
            },
            {
                "id": 264,
                "name": "Uplander",
                "brand_id": 11
            },
            {
                "id": 265,
                "name": "Venture",
                "brand_id": 11
            },
            {
                "id": 266,
                "name": "Volt",
                "brand_id": 11
            },
            {
                "id": 267,
                "name": "200",
                "brand_id": 12
            },
            {
                "id": 268,
                "name": "300",
                "brand_id": 12
            },
            {
                "id": 269,
                "name": "300M",
                "brand_id": 12
            },
            {
                "id": 270,
                "name": "Aspen",
                "brand_id": 12
            },
            {
                "id": 271,
                "name": "Caravan",
                "brand_id": 12
            },
            {
                "id": 272,
                "name": "Cirrus",
                "brand_id": 12
            },
            {
                "id": 273,
                "name": "Concorde",
                "brand_id": 12
            },
            {
                "id": 274,
                "name": "Conquest",
                "brand_id": 12
            },
            {
                "id": 275,
                "name": "Cordoba",
                "brand_id": 12
            },
            {
                "id": 276,
                "name": "Crossfire",
                "brand_id": 12
            },
            {
                "id": 277,
                "name": "E Class",
                "brand_id": 12
            },
            {
                "id": 278,
                "name": "Fifth Avenue",
                "brand_id": 12
            },
            {
                "id": 279,
                "name": "Grand Voyager",
                "brand_id": 12
            },
            {
                "id": 280,
                "name": "Imperial",
                "brand_id": 12
            },
            {
                "id": 281,
                "name": "Intrepid",
                "brand_id": 12
            },
            {
                "id": 282,
                "name": "Laser",
                "brand_id": 12
            },
            {
                "id": 283,
                "name": "LeBaron",
                "brand_id": 12
            },
            {
                "id": 284,
                "name": "LHS",
                "brand_id": 12
            },
            {
                "id": 285,
                "name": "Neon",
                "brand_id": 12
            },
            {
                "id": 286,
                "name": "New Yorker",
                "brand_id": 12
            },
            {
                "id": 287,
                "name": "Newport",
                "brand_id": 12
            },
            {
                "id": 288,
                "name": "Pacifica",
                "brand_id": 12
            },
            {
                "id": 289,
                "name": "Prowler",
                "brand_id": 12
            },
            {
                "id": 290,
                "name": "PT Cruiser",
                "brand_id": 12
            },
            {
                "id": 291,
                "name": "Sebring",
                "brand_id": 12
            },
            {
                "id": 292,
                "name": "TC by Maserati",
                "brand_id": 12
            },
            {
                "id": 293,
                "name": "Town Country",
                "brand_id": 12
            },
            {
                "id": 294,
                "name": "Voyager",
                "brand_id": 12
            },
            {
                "id": 295,
                "name": "Lanos",
                "brand_id": 13
            },
            {
                "id": 296,
                "name": "Leganza",
                "brand_id": 13
            },
            {
                "id": 297,
                "name": "Nubira",
                "brand_id": 13
            },
            {
                "id": 298,
                "name": "Charade",
                "brand_id": 14
            },
            {
                "id": 299,
                "name": "Rocky",
                "brand_id": 14
            },
            {
                "id": 300,
                "name": "200SX",
                "brand_id": 15
            },
            {
                "id": 301,
                "name": "210",
                "brand_id": 15
            },
            {
                "id": 302,
                "name": "280ZX",
                "brand_id": 15
            },
            {
                "id": 303,
                "name": "300ZX",
                "brand_id": 15
            },
            {
                "id": 304,
                "name": "310",
                "brand_id": 15
            },
            {
                "id": 305,
                "name": "510",
                "brand_id": 15
            },
            {
                "id": 306,
                "name": "720",
                "brand_id": 15
            },
            {
                "id": 307,
                "name": "810",
                "brand_id": 15
            },
            {
                "id": 308,
                "name": "Maxima",
                "brand_id": 15
            },
            {
                "id": 309,
                "name": "Pickup",
                "brand_id": 15
            },
            {
                "id": 310,
                "name": "Pulsar",
                "brand_id": 15
            },
            {
                "id": 311,
                "name": "Sentra",
                "brand_id": 15
            },
            {
                "id": 312,
                "name": "Stanza",
                "brand_id": 15
            },
            {
                "id": 313,
                "name": "DMC-12",
                "brand_id": 16
            },
            {
                "id": 314,
                "name": "400",
                "brand_id": 17
            },
            {
                "id": 315,
                "name": "600",
                "brand_id": 17
            },
            {
                "id": 316,
                "name": "Aries",
                "brand_id": 17
            },
            {
                "id": 317,
                "name": "Avenger",
                "brand_id": 17
            },
            {
                "id": 318,
                "name": "Caliber",
                "brand_id": 17
            },
            {
                "id": 319,
                "name": "Caravan",
                "brand_id": 17
            },
            {
                "id": 320,
                "name": "Challenger",
                "brand_id": 17
            },
            {
                "id": 321,
                "name": "Charger",
                "brand_id": 17
            },
            {
                "id": 322,
                "name": "Colt",
                "brand_id": 17
            },
            {
                "id": 323,
                "name": "Conquest",
                "brand_id": 17
            },
            {
                "id": 324,
                "name": "D/W Truck",
                "brand_id": 17
            },
            {
                "id": 325,
                "name": "Dakota",
                "brand_id": 17
            },
            {
                "id": 326,
                "name": "Dart",
                "brand_id": 17
            },
            {
                "id": 327,
                "name": "Daytona",
                "brand_id": 17
            },
            {
                "id": 328,
                "name": "Diplomat",
                "brand_id": 17
            },
            {
                "id": 329,
                "name": "Durango",
                "brand_id": 17
            },
            {
                "id": 330,
                "name": "Dynasty",
                "brand_id": 17
            },
            {
                "id": 331,
                "name": "Grand Caravan",
                "brand_id": 17
            },
            {
                "id": 332,
                "name": "Intrepid",
                "brand_id": 17
            },
            {
                "id": 333,
                "name": "Journey",
                "brand_id": 17
            },
            {
                "id": 334,
                "name": "Lancer",
                "brand_id": 17
            },
            {
                "id": 335,
                "name": "Magnum",
                "brand_id": 17
            },
            {
                "id": 336,
                "name": "Mirada",
                "brand_id": 17
            },
            {
                "id": 337,
                "name": "Monaco",
                "brand_id": 17
            },
            {
                "id": 338,
                "name": "Neon",
                "brand_id": 17
            },
            {
                "id": 339,
                "name": "Nitro",
                "brand_id": 17
            },
            {
                "id": 340,
                "name": "Omni",
                "brand_id": 17
            },
            {
                "id": 341,
                "name": "Raider",
                "brand_id": 17
            },
            {
                "id": 342,
                "name": "Ram 1500 Truck",
                "brand_id": 17
            },
            {
                "id": 343,
                "name": "Ram 2500 Truck",
                "brand_id": 17
            },
            {
                "id": 344,
                "name": "Ram 3500 Truck",
                "brand_id": 17
            },
            {
                "id": 345,
                "name": "Ram 4500 Truck",
                "brand_id": 17
            },
            {
                "id": 346,
                "name": "Ram 50 Truck",
                "brand_id": 17
            },
            {
                "id": 347,
                "name": "RAM C/V",
                "brand_id": 17
            },
            {
                "id": 348,
                "name": "Ram SRT-10",
                "brand_id": 17
            },
            {
                "id": 349,
                "name": "Ram Van",
                "brand_id": 17
            },
            {
                "id": 350,
                "name": "Ram Wagon",
                "brand_id": 17
            },
            {
                "id": 351,
                "name": "Ramcharger",
                "brand_id": 17
            },
            {
                "id": 352,
                "name": "Rampage",
                "brand_id": 17
            },
            {
                "id": 353,
                "name": "Shadow",
                "brand_id": 17
            },
            {
                "id": 354,
                "name": "Spirit",
                "brand_id": 17
            },
            {
                "id": 355,
                "name": "Sprinter",
                "brand_id": 17
            },
            {
                "id": 356,
                "name": "SRT-4",
                "brand_id": 17
            },
            {
                "id": 357,
                "name": "St. Regis",
                "brand_id": 17
            },
            {
                "id": 358,
                "name": "Stealth",
                "brand_id": 17
            },
            {
                "id": 359,
                "name": "Stratus",
                "brand_id": 17
            },
            {
                "id": 360,
                "name": "Viper",
                "brand_id": 17
            },
            {
                "id": 361,
                "name": "Medallion",
                "brand_id": 18
            },
            {
                "id": 362,
                "name": "Premier",
                "brand_id": 18
            },
            {
                "id": 363,
                "name": "Summit",
                "brand_id": 18
            },
            {
                "id": 364,
                "name": "Talon",
                "brand_id": 18
            },
            {
                "id": 365,
                "name": "Vision",
                "brand_id": 18
            },
            {
                "id": 366,
                "name": "308 GTB Quattrovalvole",
                "brand_id": 19
            },
            {
                "id": 367,
                "name": "308 GTBI",
                "brand_id": 19
            },
            {
                "id": 368,
                "name": "308 GTS Quattrovalvole",
                "brand_id": 19
            },
            {
                "id": 369,
                "name": "308 GTSI",
                "brand_id": 19
            },
            {
                "id": 370,
                "name": "328 GTB",
                "brand_id": 19
            },
            {
                "id": 371,
                "name": "328 GTS",
                "brand_id": 19
            },
            {
                "id": 372,
                "name": "348 GTB",
                "brand_id": 19
            },
            {
                "id": 373,
                "name": "348 GTS",
                "brand_id": 19
            },
            {
                "id": 374,
                "name": "348 Spider",
                "brand_id": 19
            },
            {
                "id": 375,
                "name": "348 TB",
                "brand_id": 19
            },
            {
                "id": 376,
                "name": "348 TS",
                "brand_id": 19
            },
            {
                "id": 377,
                "name": "360",
                "brand_id": 19
            },
            {
                "id": 378,
                "name": "456 GT",
                "brand_id": 19
            },
            {
                "id": 379,
                "name": "456M GT",
                "brand_id": 19
            },
            {
                "id": 380,
                "name": "458 Italia",
                "brand_id": 19
            },
            {
                "id": 381,
                "name": "512 BBi",
                "brand_id": 19
            },
            {
                "id": 382,
                "name": "512M",
                "brand_id": 19
            },
            {
                "id": 383,
                "name": "512TR",
                "brand_id": 19
            },
            {
                "id": 384,
                "name": "550 Maranello",
                "brand_id": 19
            },
            {
                "id": 385,
                "name": "575M Maranello",
                "brand_id": 19
            },
            {
                "id": 386,
                "name": "599 GTB Fiorano",
                "brand_id": 19
            },
            {
                "id": 387,
                "name": "599 GTO",
                "brand_id": 19
            },
            {
                "id": 388,
                "name": "612 Scaglietti",
                "brand_id": 19
            },
            {
                "id": 389,
                "name": "California",
                "brand_id": 19
            },
            {
                "id": 390,
                "name": "Enzo",
                "brand_id": 19
            },
            {
                "id": 391,
                "name": "F355",
                "brand_id": 19
            },
            {
                "id": 392,
                "name": "F40",
                "brand_id": 19
            },
            {
                "id": 393,
                "name": "F430",
                "brand_id": 19
            },
            {
                "id": 394,
                "name": "F50",
                "brand_id": 19
            },
            {
                "id": 395,
                "name": "FF",
                "brand_id": 19
            },
            {
                "id": 396,
                "name": "Mondial",
                "brand_id": 19
            },
            {
                "id": 397,
                "name": "Testarossa",
                "brand_id": 19
            },
            {
                "id": 398,
                "name": "2000 Spider",
                "brand_id": 20
            },
            {
                "id": 399,
                "name": "500",
                "brand_id": 20
            },
            {
                "id": 400,
                "name": "Bertone X1/9",
                "brand_id": 20
            },
            {
                "id": 401,
                "name": "Brava",
                "brand_id": 20
            },
            {
                "id": 402,
                "name": "Pininfarina Spider",
                "brand_id": 20
            },
            {
                "id": 403,
                "name": "Strada",
                "brand_id": 20
            },
            {
                "id": 404,
                "name": "X1/9",
                "brand_id": 20
            },
            {
                "id": 405,
                "name": "Karma",
                "brand_id": 21
            },
            {
                "id": 406,
                "name": "Aerostar",
                "brand_id": 22
            },
            {
                "id": 407,
                "name": "Aspire",
                "brand_id": 22
            },
            {
                "id": 408,
                "name": "Bronco",
                "brand_id": 22
            },
            {
                "id": 409,
                "name": "Bronco II",
                "brand_id": 22
            },
            {
                "id": 410,
                "name": "C-MAX",
                "brand_id": 22
            },
            {
                "id": 411,
                "name": "Club Wagon",
                "brand_id": 22
            },
            {
                "id": 412,
                "name": "Contour",
                "brand_id": 22
            },
            {
                "id": 413,
                "name": "Courier",
                "brand_id": 22
            },
            {
                "id": 414,
                "name": "Crown Victoria",
                "brand_id": 22
            },
            {
                "id": 415,
                "name": "E-150 and Econoline 150",
                "brand_id": 22
            },
            {
                "id": 416,
                "name": "E-250 and Econoline 250",
                "brand_id": 22
            },
            {
                "id": 417,
                "name": "E-350 and Econoline 350",
                "brand_id": 22
            },
            {
                "id": 418,
                "name": "Edge",
                "brand_id": 22
            },
            {
                "id": 419,
                "name": "Escape",
                "brand_id": 22
            },
            {
                "id": 420,
                "name": "Escort",
                "brand_id": 22
            },
            {
                "id": 421,
                "name": "Excursion",
                "brand_id": 22
            },
            {
                "id": 422,
                "name": "EXP",
                "brand_id": 22
            },
            {
                "id": 423,
                "name": "Expedition",
                "brand_id": 22
            },
            {
                "id": 424,
                "name": "Expedition EL",
                "brand_id": 22
            },
            {
                "id": 425,
                "name": "Explorer",
                "brand_id": 22
            },
            {
                "id": 426,
                "name": "Explorer Sport Trac",
                "brand_id": 22
            },
            {
                "id": 427,
                "name": "F100",
                "brand_id": 22
            },
            {
                "id": 428,
                "name": "F150",
                "brand_id": 22
            },
            {
                "id": 429,
                "name": "F250",
                "brand_id": 22
            },
            {
                "id": 430,
                "name": "F350",
                "brand_id": 22
            },
            {
                "id": 431,
                "name": "F450",
                "brand_id": 22
            },
            {
                "id": 432,
                "name": "Fairmont",
                "brand_id": 22
            },
            {
                "id": 433,
                "name": "Festiva",
                "brand_id": 22
            },
            {
                "id": 434,
                "name": "Fiesta",
                "brand_id": 22
            },
            {
                "id": 435,
                "name": "Five Hundred",
                "brand_id": 22
            },
            {
                "id": 436,
                "name": "Flex",
                "brand_id": 22
            },
            {
                "id": 437,
                "name": "Focus",
                "brand_id": 22
            },
            {
                "id": 438,
                "name": "Freestar",
                "brand_id": 22
            },
            {
                "id": 439,
                "name": "Freestyle",
                "brand_id": 22
            },
            {
                "id": 440,
                "name": "Fusion",
                "brand_id": 22
            },
            {
                "id": 441,
                "name": "Granada",
                "brand_id": 22
            },
            {
                "id": 442,
                "name": "GT",
                "brand_id": 22
            },
            {
                "id": 443,
                "name": "LTD",
                "brand_id": 22
            },
            {
                "id": 444,
                "name": "Mustang",
                "brand_id": 22
            },
            {
                "id": 445,
                "name": "Probe",
                "brand_id": 22
            },
            {
                "id": 446,
                "name": "Ranger",
                "brand_id": 22
            },
            {
                "id": 447,
                "name": "Taurus",
                "brand_id": 22
            },
            {
                "id": 448,
                "name": "Taurus X",
                "brand_id": 22
            },
            {
                "id": 449,
                "name": "Tempo",
                "brand_id": 22
            },
            {
                "id": 450,
                "name": "Thunderbird",
                "brand_id": 22
            },
            {
                "id": 451,
                "name": "Transit Connect",
                "brand_id": 22
            },
            {
                "id": 452,
                "name": "Windstar",
                "brand_id": 22
            },
            {
                "id": 453,
                "name": "ZX2 Escort",
                "brand_id": 22
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    op.drop_table('brands')
    # ### end Alembic commands ###
